mashup/config/routes.rb
Mashup::Application.routes.draw do
  
  resources :startups

  resources :students
  resources :entrepreneurs
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  root 'logins#home'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/supdatepwd',  to: 'students#updatepwd',            via: 'get'
  match '/eupdatepwd',  to: 'entrepreneurs#updatepwd',            via: 'get'
  match '/sprofile',  to: 'students#profile',            via: 'get'
  match '/allstartups',  to: 'startups#all',            via: 'get'
  match '/allstudents',  to: 'students#all',            via: 'get'
  resource :login do
    member do
      get 'callback'
      get 'logout'
    end
  end

  

end

mashup/app/models/startup.rb
class Startup < ActiveRecord::Base
    belongs_to :entrepreneur
    has_many :microposts, dependent: :destroy
    validates :name, presence: true, length: { maximum: 40 }
    validates :about, presence: true
    validates :entrepreneur_id, presence: true
    validates :founderinfo, presence: true              
    has_attached_file :pic, :styles => 
           { :medium => "300x300>", :thumb => "100x100>" }
end

mashup/app/controllers/startups_controller.rb
class StartupsController < ApplicationController
  before_action :signed_in_user,only: [:index,:new,:edit,:update,:destroy,:all,:show]
  before_action :set_startup, only: [:show, :edit, :update, :destroy]
  before_action :user_entrepreneur,only: [:index,:new,:edit,:create,:update,:destroy]
  # GET /startups
  # GET /startups.json
  def index
    #@startups = Startup.all
    @user = current_user
    @startups = @user.startups.paginate(page: params[:page])
  end

  def all
     @startups=Startup.paginate(page: params[:page])
  end 

  # GET /startups/1
  # GET /startups/1.json
  def show
    store_location
    set_startup_id(@startup)
    @microposts = @startup.microposts.paginate(page: params[:page])
    @nmicropost = @startup.microposts.build
  end

  # GET /startups/new
  def new
    @startup = Startup.new
  end

  # GET /startups/1/edit
  def edit
  end

  # POST /startups
  # POST /startups.json
  def create
    @startup = Startup.new(startup_params)
    @startup.entrepreneur_id=current_user.id

    respond_to do |format|
      if @startup.save
        format.html { redirect_to @startup }
        format.json { render action: 'show', status: :created, location: @startup }
        flash[:success] = "Startup was successfully created"
      else
        format.html { render action: 'new' }
        format.json { render json: @startup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /startups/1
  # PATCH/PUT /startups/1.json
  def update
    respond_to do |format|
      if @startup.update(startup_params)
        format.html { redirect_to @startup }
        format.json { head :no_content }
        flash[:success] = "Startup was successfully updated"
      else
        format.html { render action: 'edit' }
        format.json { render json: @startup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /startups/1
  # DELETE /startups/1.json
  def destroy
    @startup.destroy
    respond_to do |format|
      format.html { redirect_to startups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_startup
      @startup = Startup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def startup_params
      params.require(:startup).permit(:name, :link, :about, :founderinfo, :entrepreneur_id, :pic)
    end

    

   def user_entrepreneur
      @user = Users.find_by(email: current_user.email)
      if @user.type!="Entrepreneur"
         redirect_to current_user
      end
   end
end

mashup/app/helpers/startups_helper.rb
module StartupsHelper

  def set_startup_id(startup)
      $id=startup.id
  end

  def get_startup_id
      $id
  end

  def correct_startup_user(startup)
       @user = Users.find_by(email: current_user.email)
       if @user.type!="Entrepreneur"
          return false
       else
          if current_user.id==startup.entrepreneur_id
             return true
          else
             return false
          end
       end          
  end
end

mashup/app/views/startups/_form.html.erb
<%= form_for(@startup) do |f| %>
  <% if @startup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@startup.errors.count, "error") %> prohibited this startup from being saved:</h2>

      <ul>
      <% @startup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="field col-md-5">
    <%= f.label :name %><br>
    <%= f.text_field :name,:class=>"form-control" %>
  </div>
</div>
<div class="row">
  <div class="field col-md-5">
    <%= f.label :link %><br>
    <%= f.text_field :link,:class=>"form-control" %>
  </div>
</div>
<div class="row">
  <div class="field col-md-5">
    <%= f.label :about %><br>
    <%= f.text_area :about,:class=>"form-control" %>
  </div>
</div>
<div class="row">
  <div class="field col-md-5">
    <%= f.label :founderinfo %><br>
    <%= f.text_area :founderinfo,:class=>"form-control" %>
  </div>
</div>
<p>
     <b> Upload Startup Logo </b>
     <%= f.file_field :pic %>
</p>
  <div class="actions">
    <%= f.submit 'Update Profile',:class=>"btn btn-primary" %>
  </div>
<% end %>

mashup/app/views/startups/_micropost.html.erb
<ul class="list-group">
     <li class="list-group-item">
       <div class="row">
        <div class="col-md-2">
         <a href="#"><img src="img/zomato.png" class="profile_img" ></a>
          
        </div>
        <div class="col-md-8 feed_div ">
         <a href="#" class="feed">
           <p class="feed_news"><%= micropost.content %></p>
         </a>
          
        </div>
        <div class="col-md-2">
         <h6>Posted <%= time_ago_in_words(micropost.created_at) %> ago</h6>
                  
        </div>
         
       </div>
     </li>
    
</ul>

mashup/app/views/startups/all.html.erb
<div class="container">
    <label>STARTUPS</label><br>

		<!-- Begin Startup -->
 <% @startups.each do |startup| %>
        <div class="row">
	<div class="col-md-3">
             <% if startup.pic_file_name %>
                <%= image_tag startup.pic.url(:thumb),:class=>"img-rounded" %>
            <% else %>
                 <%= image_tag  "profile.jpg",:class=>"img-rounded" %> 
            <% end %>
            </div>

            <div class="col-md-6">
				<div class="row">
                   <label><%=link_to startup.name,startup %></label>
                    <br>
                    <label>Description</label>
                    <p><%= startup.about %></p>
                    <label>About the Co-Founders</label>
                    <p><%= startup.founderinfo %></p>

                    <label>Links</label>
                    <p><a href=""><%= startup.link %></a></p>
                </div>
            </div>
		</div>
        <hr><!-- End Startup -->

	</div>
<% end %>
<%= will_paginate @startups %>
</div>

mashup/app/views/startups/edit.html.erb
<h1>Editing startup</h1>


<div class="row">
 <div class="col-md-offset-1">
 <%= render 'form' %>

<%= link_to 'Show', @startup %> |
<%= link_to 'Back', startups_path %>
</div>
</div>

mashup/app/views/startups/index.html.erb
<h1>Listing startups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Link</th>
      <th>About</th>
      <th>Founderinfo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @startups.each do |startup| %>
      <tr>
        <td><%= startup.name %></td>
        <td><%= startup.link %></td>
        <td><%= startup.about %></td>
        <td><%= startup.founderinfo %></td>
        <td><%= link_to 'Show', startup %></td>
        <td><%= link_to 'Edit', edit_startup_path(startup) %></td>
        <td><%= link_to 'Destroy', startup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <%= will_paginate @startups %>
  </tbody>
</table>

<br>

<%= link_to 'New Startup', new_startup_path %>

mashup/app/views/startups/new.html.erb
<h1>New startup</h1>

<%= render 'form' %>

<%= link_to 'Back', startups_path %>

mashup/app/views/startups/show.html.erb
<!-- Begin Profile -->
        <div class="row">
      <div class="col-md-3 col-md-offset-1 well" align="center">
              <% if @startup.pic_file_name %>
                <%= image_tag @startup.pic.url(:thumb) %><br><br>
              <% else %>
                 <%= image_tag("profile.jpg") %><br><br> 
              <% end %>
                <% if correct_startup_user(@startup) %>
                <%= link_to 'Edit Info', edit_startup_path(@startup), class: "btn btn-default" %><br>
                <% end %>
                <a href="#"><h2><%= @startup.name %></h2></a>
                    <br>
                    <label>About</label>
                    <p>
                      <%= @startup.about %>
                    </p>
                   
                    <label>Link</label>
                    <p>
                      <%= @startup.link %>
                    </p>

                      
                    
                    <label>Founder Info</label>
                    <p><%= @startup.founderinfo %></p><br>
                     
    
            </div>

            <div class="col-md-7">
              <% if correct_startup_user(@startup) %>
                <div class="container">
                  <%= form_for(@nmicropost) do |f| %>
                            <div class="field col-md-6">
                               <%= f.text_area :content, placeholder: "Compose new micropost...",:class=>"form-control" %>
                            </div>
                            <%= f.submit "Post", class: "btn btn-large btn-primary" %>
                  <% end %><br><br>
              
                  <% if @startup.microposts.any? %>
                            <h3>Microposts (<%= @startup.microposts.count %>)</h3>
 
    
                  <% end %>

               </div>
           <% end %>
              
<div >
   
    <ul class="list-group">
     <% @microposts.each do |micropost| %>
     <li class="list-group-item">
       <div class="row">
        <div class="col-md-2">
         <% if @startup.pic_file_name %>
                 <a href="#"><%= image_tag @startup.pic.url(:thumb) %></a>
         <% else %>
                 <%= image_tag("icons/profile.jpg") %><br><br> 
        <% end %>
          
        </div>
        <div class="col-md-8 feed_div ">
         <a href="#" class="feed">
           <p class="feed_news"><%= micropost.content %></p>
         </a>
          
        </div>
        <div class="col-md-2">
         <h6>Posted <%= time_ago_in_words(micropost.created_at) %> ago</h6>
         
          
        </div>
         
       </div>
     </li>
      
    </ul>
    <% end %>
    <%= will_paginate @microposts %>
  
</div>
        
                </div>
            </div>
    </div>

        <!-- End Profile -->