mashup/config/routes.rb
Mashup::Application.routes.draw do
  
  resources :startups

  resources :students
  resources :entrepreneurs
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  root 'logins#home'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/supdatepwd',  to: 'students#updatepwd',            via: 'get'
  match '/eupdatepwd',  to: 'entrepreneurs#updatepwd',            via: 'get'
  match '/sprofile',  to: 'students#profile',            via: 'get'
  match '/allstartups',  to: 'startups#all',            via: 'get'
  match '/allstudents',  to: 'students#all',            via: 'get'
  resource :login do
    member do
      get 'callback'
      get 'logout'
    end
  end

  

end

mashup/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="">Founder Dating</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    
    
    <% if signed_in? || lcurrent_user %>
    <ul class="nav navbar-nav">
        <li><a href="/allstartups">Startups</a></li>
        <li><a href="/allstudents">Students</a></li>
    </ul>
    
    <ul class="nav navbar-nav navbar-right">
     <li><%= link_to "Home",current_user %></a></li>
     <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                
                <% if user_type=="Student" %>
                <li><%= link_to "Profile", "/sprofile" %></li>
                <li><%= link_to "Update Profile", edit_student_path(current_user) %></li>
                <li><%= link_to "Update Password", "/supdatepwd" %></li>
                <% else %>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Update Password", "/eupdatepwd" %></li>
                <% end %>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", logout_login_path, :method => :get  %>
                </li>
              </ul>
            </li>
    </ul>
  <!--
    <form class="navbar-form navbar-right" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
    </form> -->
   <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sign in", "/login" %></li>
          </ul>
   <% end %>
  </div><!-- /.navbar-collapse -->
</nav>

mashup/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mashup</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
     <% if !current_user %>
     <% else %>
       <%= render 'layouts/header' %>
     <% end %>
     
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>
<%= yield %>

</body>
</html>