mashup/config/routes.rb
Mashup::Application.routes.draw do
  
  resources :startups

  resources :students
  resources :entrepreneurs
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  root 'logins#home'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/supdatepwd',  to: 'students#updatepwd',            via: 'get'
  match '/eupdatepwd',  to: 'entrepreneurs#updatepwd',            via: 'get'
  match '/sprofile',  to: 'students#profile',            via: 'get'
  match '/allstartups',  to: 'startups#all',            via: 'get'
  match '/allstudents',  to: 'students#all',            via: 'get'
  resource :login do
    member do
      get 'callback'
      get 'logout'
    end
  end

  

end

mashup/app/models/entrepreneur.rb
class Entrepreneur < ActiveRecord::Base
   has_many :startups, dependent: :destroy
   before_save { self.email = email.downcase }
   validates :fname, presence: true, length: { maximum: 20 }
   validates :lname, presence: true, length: { maximum: 20 }
   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
   has_secure_password
   validates :password, length: { minimum: 6 }

   def Entrepreneur.new_remember_token
    SecureRandom.urlsafe_base64
   end

   def Entrepreneur.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
   end

  private

   def create_remember_token
     self.remember_token = Entrepreneur.encrypt(Entrepreneur.new_remember_token)
   end
end

mashup/app/controllers/entrepreneurs_controller.rb
class EntrepreneursController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update,:show]
  before_action :correct_user,   only: [:edit, :update]
  def new
  if !current_user
     @user = Entrepreneur.new
     store_location
  else
    redirect_to current_user
  end
  end

  def show
    @user = Entrepreneur.find(params[:id])
    @startups = @user.startups.paginate(page: params[:page])
    @microposts = Micropost.paginate(page: params[:page])
  end

  def updatepwd
    @user = current_user
  end

  def create
    @entrepreneur = Entrepreneur.new(user_params)    
    if @entrepreneur.save
      # Handle a successful save.
      @user=Users.new
      if lcurrent_user
         @string=current_user['siteStandardProfileRequest']['url'].scan(/id=+(\d+)/)[0][0]
         @entrepreneur.update_attribute(:linkedin_id,@string)
         @user.update_attribute(:linkedin_id,@string)
      end
      @user.update_attribute(:email,@entrepreneur.email)
      @user.update_attribute(:type,"Entrepreneur")
      @user.save
      sign_in(@entrepreneur,"Entrepreneur")
      flash[:success] = "Make your own startup to reach out to other users"
      redirect_to current_user
    else
      #redirect_back_or "/login"
      @user=@entrepreneur
      render 'new'
    end
  end

  def update
    @user = Entrepreneur.find(params[:id])
    if @user.update_attributes(user_params)
      # Handle a successful update.
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'updatepwd'
    end
  end

  private

    def user_params
      params.require(:entrepreneur).permit(:fname, :lname, :email,:password,:password_confirmation)
    end
end

mashup/app/helpers/entrepreneurs_helper.rb
module EntrepreneursHelper
end

mashup/app/views/entrepreneurs/new.html.erb
<% provide(:title, 'Sign up') %>
<% if lcurrent_user %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>

      <%= f.label :fname,"First Name" %>
      <%= f.text_field :fname,:value => lcurrent_user['firstName'],:class=>"form-control" %>

      <%= f.label :lname,"Last Name" %>
      <%= f.text_field :lname,:value => lcurrent_user['lastName'],:class=>"form-control" %>

      <%= f.label :email %>
      <%= f.text_field :email,:class=>"form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password,:class=>"form-control" %>

      <%= f.label :password_confirmation, "Re-enter Password" %>
      <%= f.password_field :password_confirmation,:class=>"form-control" %>
      <br>
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
<% else %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>

      <%= f.label :fname,"First Name" %>
      <%= f.text_field :fname,:class=>"form-control" %>

      <%= f.label :lname,"Last Name" %>
      <%= f.text_field :lname,:class=>"form-control" %>

      <%= f.label :email %>
      <%= f.text_field :email,:class=>"form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password,:class=>"form-control" %>

      <%= f.label :password_confirmation, "Re-enter Password" %>
      <%= f.password_field :password_confirmation,:class=>"form-control" %>
      <br>
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
 <h2>or</h2>
  Sign Up with LinkedIn
  <%=button_to "Sign Up", login_path, :method => :post, class: "btn btn-large btn-primary" %>
<% end %>

mashup/app/views/entrepreneurs/show.html.erb
<div class="container ">

      <div class="col-md-2" style="padding-top:20px;">
       <% if @user==current_user %>
        <label>My Startups</label>
       <% else %>
        <label>Startups</label>
       <% end %>
        <ul class="nav nav-stacked" style="border:solid 1px #e7e7e7;">
         <% @startups.each do |startup| %>
          <li style="background-color:#F8F8F8;"><%= link_to (startup.name), startup,{ :style => 'color:#777' } %></li>
         <% end %>
         <%= will_paginate @startups %>
        <% if @user==current_user %>
         <li style="background-color:#F8F8F8;"><%= link_to 'Add New Startup',new_startup_path,{ :style => 'color:#777' } %></li>
        <% end %>
        </ul>        
      </div>

      <div class="col-md-10">

      
        <h3>News Feed</h3>
        <br>
         <ul class="list-group">
     <% @microposts.each do |micropost| %>
     <li class="list-group-item">
       <div class="row">
        <div class="col-md-2">
         <%  @startup=Startup.find(micropost.startup_id)%>
        <% if @startup.pic_file_name %>
         <a href="#"><%= image_tag @startup.pic.url(:thumb) %></a>
        <% else %>
                 <%= image_tag("profile.jpg") %><br><br> 
        <% end %>  
          
        </div>
        <div class="col-md-8 feed_div ">
         <a href="#" class="feed">
           <p class="feed_news"><%= micropost.content %></p>
         </a>
          
        </div>
        <div class="col-md-2">
         <h6>Posted <%= time_ago_in_words(micropost.created_at) %> ago</h6>
         
          
        </div>
         
       </div>
     </li>
      
    </ul>
    <% end %>
    <%= will_paginate @microposts %>
      </div>

mashup/app/views/entrepreneurs/updatepwd.html.erb
<% provide(:title, "Update Password") %>
<h1>Update your Password</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :password %>
      <%= f.password_field :password,:class=>"form-control" %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation,:class=>"form-control"%>
      <br>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>