mashup/config/routes.rb
Mashup::Application.routes.draw do
  
  resources :startups

  resources :students
  resources :entrepreneurs
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  root 'logins#home'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/supdatepwd',  to: 'students#updatepwd',            via: 'get'
  match '/eupdatepwd',  to: 'entrepreneurs#updatepwd',            via: 'get'
  match '/sprofile',  to: 'students#profile',            via: 'get'
  match '/allstartups',  to: 'startups#all',            via: 'get'
  match '/allstudents',  to: 'students#all',            via: 'get'
  resource :login do
    member do
      get 'callback'
      get 'logout'
    end
  end

  

end

mashup/app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  helper_method :lcurrent_user

  def home
     if current_user
        redirect_to current_user
     end
  end

  def show
   if lcurrent_user
   @string=lcurrent_user['siteStandardProfileRequest']['url'].scan(/id=+(\d+)/)[0][0]
   if !@user=Users.find_by(linkedin_id: @string)
      reset_session
      flash[:alert] = "Please sign up first"
      redirect_to "/"
   elsif @user.type=="Student"
      @student=Student.find_by(linkedin_id: @string)
      sign_in(@student,"Student")
      redirect_to @student
   elsif @user.type=="Entrepreneur"
      @entrepreneur=Entrepreneur.find_by(linkedin_id: @string)
      sign_in(@entrepreneur,"Entrepreneur")
      redirect_to @entrepreneur 
   end
     elsif signed_in?
      redirect_to current_user
   end
  end

  def create
    request_token = consumer.get_request_token(:oauth_callback => callback_login_url)
    Rails.cache.write(request_token.token, request_token.secret)
    redirect_to request_token.authorize_url
  end

  def callback
    request_token = OAuth::RequestToken.new(consumer, params[:oauth_token], Rails.cache.read(params[:oauth_token]))
    access_token = request_token.get_access_token(:oauth_verifier => params[:oauth_verifier])
    session[:access_token] = access_token.token
    session[:access_token_secret] = access_token.secret
    redirect_back_or "/login"
  end

  def logout
    sign_out
    reset_session
    redirect_to "/"
  end

  private
  CONSUMER_KEY = {
    :key => "efh3x5xkpxq0",
    :secret => "BWA2xEepmqKzhBfC"
  }
  CONSUMER_OPTIONS = { :site => 'https://api.linkedin.com',
                     :authorize_path => '/uas/oauth/authorize',
                     :request_token_path => '/uas/oauth/requestToken',
                     :access_token_path => '/uas/oauth/accessToken',
 :scope => 'r_fullprofile r_emailaddress r_network', :fields => ["id", "email-address", "first-name", "last-name", "headline"] }

  def consumer
    @consumer ||= OAuth::Consumer.new( CONSUMER_KEY[:key], CONSUMER_KEY[:secret], CONSUMER_OPTIONS)
  end

  def access_token
    if session[:access_token]
      @access_token ||= OAuth::AccessToken.new(consumer, session[:access_token], session[:access_token_secret])
    end
  end

  def lcurrent_user
    if access_token
      @current_user ||= JSON.parse(access_token.get('http://api.linkedin.com/v1/people/~', 'x-li-format' => 'json').body)
      # Pick some fields
      #fields = ['first-name', 'last-name', 'headline', 'industry', 'num-connections','email-address'].join(',')

      # Make a request for JSON data
      #json_txt = access_token.get("http://api.linkedin.com/v1/people/~:(#{fields})", 'x-li-format' => 'json').body
      #@current_user ||= JSON.parse(json_txt)
    end
    @current_user
  end
end

mashup/app/helpers/logins_helper.rb
module LoginsHelper
 
 CONSUMER_KEY = {
    :key => "efh3x5xkpxq0",
    :secret => "BWA2xEepmqKzhBfC"
  }
  CONSUMER_OPTIONS = { :site => 'https://api.linkedin.com',
                     :authorize_path => '/uas/oauth/authorize',
                     :request_token_path => '/uas/oauth/requestToken',
                     :access_token_path => '/uas/oauth/accessToken' }

  def consumer
    @consumer ||= OAuth::Consumer.new( CONSUMER_KEY[:key], CONSUMER_KEY[:secret], CONSUMER_OPTIONS)
  end

  def access_token
    if session[:access_token]
      @access_token ||= OAuth::AccessToken.new(consumer, session[:access_token], session[:access_token_secret])
    end
  end

  def lcurrent_user
    if access_token
      @current_user ||= JSON.parse(access_token.get('http://api.linkedin.com/v1/people/~', 'x-li-format' => 'json').body)
    end
    @current_user
  end

end

mashup/app/views/logins/home.html.erb
<style>
      body
      {
        overflow-x:hidden;
        padding-top: 0px;
      }
    </style>

    <style>
      .back-to-top 
      {
      position: fixed;
      bottom: 3em;
      right: 40px;
      height:100px;
      width: 100px;
      text-decoration: none;
      /*color: #000000;*/
      background-image: url('<%= asset_path("arrow_up_1.png") %>');
      /*font-size: 12px;*/
      padding: 1em;
      opacity:0.7;
      display: none;
      }

      .back-to-top:hover 
      {    
          opacity:1;
      }

     

    </style>

    <script>

        $(function() 
    {
        
        $('.div1 .row .header2 a').bind('click',function(event)
        {
            var $anchor = $(this);

            $('html, body').stop().animate(
            {
                scrollTop: $($anchor.attr('href')).offset().top
            }, 1000);
            event.preventDefault();
        });
    });


      jQuery(document).ready(function() {
      var offset = 220;
      var duration = 500;
      jQuery(window).scroll(function() {
          if (jQuery(this).scrollTop() > offset) {
              jQuery('.back-to-top').fadeIn(duration);
          } else {
              jQuery('.back-to-top').fadeOut(duration);
          }
      });
      
      jQuery('.back-to-top').click(function(event) {
          event.preventDefault();
          jQuery('html, body').animate({scrollTop: 0}, duration);
          return false;
      })
  });


    </script>

  </head>
  <body>
   <div class="div1">
    <div class="row">
    
     <div class="col-md-6 col-md-offset-6 header2" style="">
      <a href="#about" class="navigate">About Us</a>&nbsp&nbsp
      <a href="#entrepreneur" class="navigate">Entrepreneur</a>&nbsp&nbsp
      <a href="#student" class="navigate">Student</a>&nbsp&nbsp
      <a href="#contact" class="navigate">Contact</a>&nbsp&nbsp&nbsp
      <a href="" class="navigate-login" data-toggle="modal" data-target="#LoginModal">
        Login
      </a>
      <a href="" class="navigate-register" data-toggle="modal" data-target="#RegisterModal">
        Register Now!
      </a>

       
     </div>
      
    </div>
    <div class="center ">
     <div class="row">
      <div class="col-md-6 col-md-offset-1">
       <p class="home">START <br>TO STARTUP AT <font color="#09b7dc">FOUNDER DATING</font></p>
        
      </div>
       
     </div>
    
    
      
    </div>
     
   </div>

   <div id="about" class="div2 row" style="margin-top:0px;">
    <div align="center " class="col-md-10 col-md-offset-1">
     <h1>WE AT <font color="#09b7dc">FOUNDER DATING</font> LET YOU</h1>
     <div class="row header3">
      <div class="col-md-4" align="center">
       <%= image_tag("startups.png") %><br><br>
       <h3>CONNECT AND LET YOU INTERACT WITH STARTUPS</h3>

        
      </div>
      <div class="col-md-4">
       <%= image_tag("search.png") %><br><br>
       <h3>HELP YOU LOOK FOR THE RIGHT PERSON</h3>
        
      </div>
      <div class="col-md-4">
       <%= image_tag("incubator.png") %><br><br>
       <h3>CONNECT YOU TO VC'S AND INCUBATORS</h3>
        
      </div>
      
       
     </div>
      
    </div>
   
     
   </div>


   <div id="entrepreneur" class="div3 row" style="margin-top:0px;">
    <div align="center " class="col-md-10 col-md-offset-1">
     <h1>WHAT DO WE GIVE TO <font color="#09b7dc">ENTREPRENEURS</font> ?</h1>
     <div class="row header3">
      <h3>ADD YOUR INTERNSHIP REQUIREMENTS, SEARCH FOR PEOPLE WITH SKILLS YOU NEED AND STRENGTHEN YOUR STARTUP.</h3>
      
       
     </div>
      
    </div>
   
     
   </div>
   

   <div id="student" class="div2 row" style="margin-top:0px;">
    <div align="center " class="col-md-10 col-md-offset-1">
     <h1>WHAT DO WE GIVE TO <font color="#09b7dc">STUDENTS</font> ?</h1>
     <div class="row header3">
     <h3>WITH VARIOUS INTERNSHIP OPPORTUNITIES, PEOPLE WITH SKILLS AND UPDATES FROM STARTUPS, YOU CAN START YOUR WAY TO BECOME AN ENTREPRENEUR.</h3>
      
      
       
     </div>
      
    </div>
   
     
   </div>
   <!-- <div class="div3 row" align="CENTER" >
    <h1><font color="#fff">STARTUPS ON BOARD</font></h1><br><br>
    <div class="row startups">
     <div class="col-md-4" align="center">
     <a href="#"><img src="img/gharpay.png"></a>
     
      
    </div>
    <div class="col-md-4" align="center">
     <a href="#"><img src="img/groupon.png"></a>
     
      
    </div>
    <div class="col-md-4" align="center">
     <a href="#"><img src="img/zomato.png" ></a>

      
    </div>

      
    </div>
    <div class="row startups">
     <div class="col-md-4" align="center">
     <a href="#"><img src="img/gharpay.png"></a>
     
      
    </div>
    <div class="col-md-4" align="center">
     <a href="#"><img src="img/groupon.png"></a>
     
      
    </div>
    <div class="col-md-4" align="center">
     <a href="#"><img src="img/zomato.png" ></a>

      
    </div>

      
    </div>
    
     
   </div> -->

   <div id="contact" class="div4 row" align="center">
   <h1><font color="#fff">GET TO US</font></h1>
   <div class="row header2">
    <div class="col-md-6 ">
    <h4>FOLLOW US</h4>
     <button class="btn-circle"><div class="icon"><i class="fa fa-facebook"></i></div></button>&nbsp&nbsp&nbsp<button class="btn-circle"><div class="icon"><i class="fa fa-twitter"></i></div></button>&nbsp&nbsp&nbsp<button class="btn-circle"><div class="icon"><i class="fa fa-linkedin"></i></div></button>&nbsp&nbsp&nbsp<button class="btn-circle"><div class="icon"><i class="fa fa-google-plus"></i></div></button>
      
    </div>
    <div class="col-md-6" align="center">
     <h3>Know More about Us</h3>
     <a href="#" class="navigate">BITS Homepage</a>
     <a href="#" class="navigate">CEL WEBSITE</a>
      
    </div>

     
   </div>
     <div class="header2 row" align="center">
     <h6>brought to you by</h6>
     <h5>CENTER FOR ENTREPRENEURIAL LEADERSHIP, BITS PILANI</h5>

      
    </div>
   </div>

   

    <!-- Modal -->
    <div class="modal fade" id="LoginModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Login</h4>
          </div>
          <div class="modal-body">

    
            <%= form_for(:session, url: sessions_path) do |f| %>
		     <div class="form-group">
		      <%= f.label :email %>
		      <%= f.text_field :email,:class=>"form-control",:placeholder=>"Enter email" %>
		     </div>

		    <div class="form-group">
		      <%= f.label :password %>
		      <%= f.password_field :password,:class=>"form-control",:placeholder=>"Enter Password" %>
		    </div>

		      <%= f.submit "Sign in", class: "btn btn-default" %>
		    <% end %>

            
            <h4>Or</h4>
            <%=button_to "Login with LinkedIn", login_path, :method => :post,:class=>"btn btn-info" %>
            
          </div>
          
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
       
    <!-- Modal -->
    <div class="modal fade" id="RegisterModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Join the Revolution NOW!</h4>
          </div>
          <div class="modal-body">

            <div class="row">
              <div class="col-md-4 col-md-offset-1">
                <%= link_to 'Register as a Student',"/students/new", class: "btn btn-success" %>

              </div>
              <div class="col-md-4 col-md-offset-1">
                <%= link_to 'Register as an Entrepreneur',"/entrepreneurs/new", class: "btn btn-success" %>

              </div>
            </div>
              
            
          </div>
          
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <a href="#" class="back-to-top"></a>
     <script src="js/bootstrap.min.js"></script>
  </body>

mashup/app/views/logins/new.html.erb
<h1>Login#new</h1>
<p>Find me in app/views/login/new.html.erb</p>

mashup/app/views/logins/show.html.erb
<h1>Sign in</h1>



<div class="row">
  <div class="span6 offset3">
    <%= form_for(:session, url: sessions_path) do |f| %>
     <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email,:class=>"form-control",:placeholder=>"Enter email" %>
    </div>
     <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password,:class=>"form-control",:placeholder=>"Enter Password" %>
    </div>
      <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
    <% end %>

    <p>New user? <%= link_to "Sign up now!", root_path %></p>
  </div>
</div>

<h2>or</h2>
  <%=button_to "Login with LinkedIn", login_path, :method => :post,:class=>"btn btn-info" %>
</div>